# Travis CI configuration for LTAPI Example plugin
language: cpp
# The matrix specifies full os/dist settings, this root definition is only to avoid Travis informational output
os: linux
dist: bionic

jobs:
  include:
    # --- Linux ---
    - name: Linux build
      os: linux
      dist: bionic                  # Ubuntu 18.04
      addons:
        apt:
          packages:
          - freeglut3-dev
      script:
      - cd Example                  # for LTAPI we build the example plugin
      - mkdir build-lin && cd build-lin
      - cmake -G "Unix Makefiles" ..
      - make
      before_deploy:                # Determine tag for deployment
        - if [[ "$TRAVIS_TAG" = "" ]]; then export TRAVIS_TAG="travis_build"; fi
      deploy:
        provider: releases          # GitHub OAuth token provided in GITHUB_TOKEN environment variable in Travis' branch settings
        edge: true                  # opting in to dpl v2
        name: LTAPI Example Plugin
        tag_name: "$TRAVIS_TAG"
        on:
          all_branches: true
        cleanup: false
        draft: true
        prerelease: true
        overwrite: true
        file: "LTAPIExample-lin.xpl"
